import { Inter } from "next/font/google";
import "./globals.css";
import Topbar from "./component/topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PT Dejeha Anja Indonesia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Topbar />
        {/*  */}
        {children}
        {/* <div style={{ height: 200, background: "grey" }}>
          <h1>halaman footer</h1>
        </div> */}
      </body>
    </html>
  );
}
